### ISSUE TITLE
operands could not be broadcast together in prep_del.py, line 120

### ISSUE THREAD

**Issue by jmarclegoff** [igmhub/pyLyA#104] opened 2017-05-19 10:04 UTC
do_xcf.py fails in prep_del.py while do_cf.py works on the same --in-dir delta/

/Users/legoff/ana/pyLyA<5>python bin/do_xcf.py --in-dir delta/ --no-project --out cf.fits --drq delta/../QSO1024.new.fits
read 0 of 1 0
Traceback (most recent call last):
  File "bin/do_xcf.py", line 146, in <module>
    ll,st, wst   = prep_del.stack(xcf.dels,delta=True)
  File "/Users/legoff/ana/pyLyA/py/pylya/prep_del.py", line 120, in stack
    st[:len(c)]+=c
ValueError: operands could not be broadcast together with shapes (214,) (215,) (214,)

**Comment by londumas** [comment] 2017-05-19 10:08
@jmarclegoff could you check that in the auto and in the cross the different attributes have the same values ?
All attributes used in  def stack(data,delta=False).
For example:
d.ll,
forest.lmin,
forest.dll

**Comment by ngbusca** [comment] 2017-05-19 10:10
@londumas There's a problem when calculating the stack, most likely there's a check that the bins don't go over the size of the array that holds the stack.

**Comment by ngbusca** [comment] 2017-05-19 10:10
I meant that the check is missing

**Comment by londumas** [comment] 2017-05-19 10:11
I agree that there must be a bin overflow. Before the check, we need to understand why it happens.

**Comment by ngbusca** [comment] 2017-05-19 12:19
@jmarclegoff can you confirm that your deltas are all on a common grid uniform in log-lambda?

**Comment by jmarclegoff** [comment] 2017-05-19 14:33
The grid that is uniform in Mpc/h and not in log-lambda

**Comment by ngbusca** [comment] 2017-05-19 14:35
pylya assumes a grid that is uniform in loglam and the same for all lines of sight (they don't need to start and end at the same bin though)

**Comment by londumas** [comment] 2017-05-19 14:37
I am not sure this is true @ngbusca. Where do you see such supposition in the correlations calculations ?

**Comment by ngbusca** [comment] 2017-05-19 14:38
in do_xcf you use this assumption to get forest.dll, forest.lmin, etc. that are required in stack()

**Comment by ngbusca** [comment] 2017-05-19 14:39
You could run do_xcf without a uniform grid in loglam, but then they stack function doesn't work...

**Comment by jmarclegoff** [comment] 2017-05-19 14:41
@ngbusca : This is what I did when I run with  --no-remove-mean-lambda-obs

**Comment by londumas** [comment] 2017-05-19 14:42
I am not sure of that:
z_min_pix = sp.amin( sp.append([z_min_pix],z) )
z_max_pix = sp.amax( sp.append([z_max_pix],z) )
 bin_size_ll = sp.amin( sp.append([bin_size_ll],[d.ll[ii]-d.ll[ii-1] for ii in range(1,d.ll.size)]) )

and
forest.lmin  = sp.log10( (z_min_pix+1.)*args.lambda_abs )
forest.lmax  = sp.log10( (z_max_pix+1.)*args.lambda_abs )
forest.dll = bin_size_ll

**Comment by ngbusca** [comment] 2017-05-19 14:43
in the stack function:

bins=((d.ll-forest.lmin)/forest.dll+0.5).astype(int)

so you assume that the bins are uniform in loglam

**Comment by londumas** [comment] 2017-05-19 17:05
No, I don't think so. Or I am missing something obvious.
I just get the index of the bin of the grid the stack is defined on.

**Comment by londumas** [comment] 2017-05-20 09:26
@jmarclegoff , if you don't find the problem, I can try to solve it.
You would just have to give me the two files and the command line you use.

**Comment by londumas** [comment] 2017-05-22 08:54
@jmarclegoff It could simply be caused by a rounding problem.
I take the min of redshift of pixels, not of lambda_obs.

**Comment by jmarclegoff** [comment] 2017-05-22 16:33
I put prints in prep_del.py to investigate why it crashes in stack().
I have  lmin= 3.5070671055 lmax = 3.74613098232 dll = 0.00111861556251
which makes
nstack = int((forest.lmax-forest.lmin)/forest.dll)+1		= int(213.7) + 1 = 214
since    st = sp.zeros(nstack)	we have     len(st) = 214
since  bins=((d.ll-forest.lmin)/forest.dll+0.5).astype(int)
   when d.ll reaches forest.lmax  bins is  int(213.7 + 0.5) = 214 
 so     c = sp.bincount(bins,weights=de*we)      has a length of 215 
so   len(c) > len (st)   and st[:len(c)]+=c   crashes

It looks like 
nstack = int((forest.lmax-forest.lmin)/forest.dll)+1 
should be replaced by
nstack = int((forest.lmax-forest.lmin)/forest.dll+0.5)+1
to match
bins=((d.ll-forest.lmin)/forest.dll+0.5).astype(int)

If I do that the code does not crash anymore.

**Comment by londumas** [comment] 2017-05-23 10:13
fixed in fix_issue_104

**Closed by londumas** 2017-05-23 10:13 UTC
