### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by mubecks** [igmhub/pyLyA#119] opened 2017-06-22 09:08 UTC
Hello I am a new user of pyLyA code.
When I tried to run do_deltas.py with mode spec, I got this value error message.
I reinstalled numpy and scipy with conda but still same error.

iteration:  0
done
/home/sjc2/.local/lib/python2.7/site-packages/pyLyA-0.9-py2.7.egg/pylya/prep_del.py:25: RuntimeWarning: invalid value encountered in divide
Traceback (most recent call last):
  File "bin/do_deltas.py", line 239, in <module>
    forest.mean_cont = interp1d(ll_rest[wmc>0.], forest.mean_cont(ll_rest[wmc>0.]) * mc[wmc>0.], fill_value = "extrapolate")
  File "/home/sjc2/anaconda2/lib/python2.7/site-packages/scipy/interpolate/interpolate.py", line 444, in __init__
    self._y = self._reshape_yi(self.y)
  File "/home/sjc2/anaconda2/lib/python2.7/site-packages/scipy/interpolate/polyint.py", line 111, in _reshape_yi
    return yi.reshape((yi.shape[0], -1))
ValueError: total size of new array must be unchanged

**Comment by ngbusca** [comment] 2017-06-22 11:31
Could you post the exact command you are trying to run and attach a text file with your list of spec files?

**Comment by mubecks** [comment] 2017-06-23 04:39
I used this command with my path
python bin/do_deltas.py --in-dir data/ --drq ../DR14Q_v1_1.fits --out-dir deltas/ --mode spec

and spec files are about 50,000
spec-(plate)-(mjd)-(fiberid).fits

**Comment by ngbusca** [comment] 2017-06-23 04:41
Could you attach a text file with your list of spec files?

**Comment by mubecks** [comment] 2017-06-26 02:24
I don't know how to attach a file here so just write down here.
spec-3586-55181-0038.fits
spec-3586-55181-0098.fits
spec-3586-55181-0158.fits
...
spec-3586-55181-0958.fits
,
spec-3587-55182-0100.fits
spec-3587-55182-0108.fits
spec-3587-55182-0140.fits
...
spec-3587-55182-0945.fits

and so on.

**Comment by ngbusca** [comment] 2017-06-28 07:36
it looks like you code is rejecting all the input quasars. To confirm, can you do 

```
grep accepted input.log
```

can you give me the full path from where you obtained the spec files?

**Comment by mubecks** [comment] 2017-06-28 09:58
I did 'grep accepted input.log' then nothing is printed on terminal.

Do you mean the path where spec files are downloaded on my computer?

**Comment by ngbusca** [comment] 2017-06-28 10:29
Ok, this means that the code is rejecting all quasars, we need to understand why. One possibility is that you have spec files from DR12 and are using the DR14Q vac, so there is an inconsistency in the THING_ID. To know if this is the case I need to know from where you got your spec files. You can also try using DR12Q instead of DR14Q.

**Comment by mubecks** [comment] 2017-06-29 04:47
Okay I understood, but I used spec files of DR14 quasar and also used  quasar catalog of DR14.

**Comment by ngbusca** [comment] 2017-06-29 07:02
Can you please attach the input.log file?

**Comment by mubecks** [comment] 2017-06-29 07:08
Okay, Here I attatch the zip file of input.log.
[input.log.gz](https://github.com/igmhub/pyLyA/files/1111127/input.log.gz)

**Comment by ngbusca** [comment] 2017-06-29 07:22
Could you please post the exact website from where you've downloaded your spec files?

**Comment by mubecks** [comment] 2017-06-29 07:25
data.sdss.org/sas/ebosswork/eboss/spectro/redux/v5_10_0/spectra/full/

I think this is the website of my files.

**Comment by ngbusca** [comment] 2017-06-29 09:43
I've finally managed to reproduce your problem. It was indeed a bug, can you update your master branch and try again?

**Comment by mubecks** [comment] 2017-06-29 10:24
Wow, do_deltas.py worked!
Now I am trying do_cf.py.
I appreciate so much!!

**Comment by ngbusca** [comment] 2017-06-29 10:30
fixed on master

**Closed** 2017-06-29 10:30 UTC
